/*
*   SAMT for Sonic Adventure 2 (PC, 2012) - '/config.h'
*
*   Description:
*     For loading, reading, modifying, & saving '.ini' configuration files. The most common use
*   is reading user-config files generated by the Mod Manager.
*
*   Notes:
*     - Use 'NULL' as the section name to access global keys (items with no section)
*     - This can parse files with comments and padding, but they will be discarded when loading
*       files that contain them. Eg: 'key = value ; comment' -> 'key=value'
*
*   Disambiguations:
*     - header          : the main pointer for a config structure
*     - section         : a config section
*     - item            : a key/value pair
*     - entry           : a section/item pair
*/
#ifndef H_SAMT_CONFIG
#define H_SAMT_CONFIG

EXTERN_START

/********************************/
/*  Opaque Types                */
/********************************/
/****** MSVC stdio ******************************************************************************/
typedef struct _iobuf               FILE; /* msvc std file type                                 */

/****** Config **********************************************************************************/
typedef struct mt_config            mt_config;      /* config header                            */
typedef struct mt_config_sect       mt_config_sect; /* config section                           */
typedef struct mt_config_item       mt_config_item; /* config item                              */

/********************************/
/*  Prototypes                  */
/********************************/
/************************************************************************************************/
/*
*   Open/Save/Free
*/
/****** Open ************************************************************************************/
/*
*   Description:
*     Open an existing config file (.ini) - or create a new, empty config structure. With 2
*   parameter path variant.
*
*   Examples:
*     - mtConfigOpen( "path/to/file.ini" );             // single para path
*     - mtConfigOpen( NULL );                           // new config structure
*     - mtConfigOpen2( mtGetModPath(), "config.ini" );  // two para path
* 
*   Parameters:
*     - puPath      : path to ini file/directory                                 [opt: nullptr]
*     - puName      : name of ini file
*
*   Returns:
*     Config header with contents of ini file; or new empty header.
*/
mt_config* mtConfigOpen(  const c8* puPath );
mt_config* mtConfigOpen2( const c8* puPath, const c8* puName );

/****** Save ************************************************************************************/
/*
*   Description:
*     Save a config structure to a file.
*
*   Examples:
*     - mtConfigSave(  pHead, "path/to/file.ini" );            // single para path
*     - mtConfigSave2( pHead, mtGetModPath(), "config.ini" );  // two para path
*
*   Notes:
*     - When saving to a file, all comments and padding will be lost as they're discarded when
*       the file is loaded.
*
*   Parameters:
*     - pHead       : config structure
*     - puPath      : path to file/directory
*     - puName      : name of file
*
*   Returns:
*     'true' if the file was successfully saved, or there were no changes to save;
*   or 'false' on failure.
*/
bool    mtConfigSave(  const mt_config* pHead, const c8* puPath );
bool    mtConfigSave2( const mt_config* pHead, const c8* puPath, const c8* puName );

/****** Free ************************************************************************************/
/*
*   Description:
*     Free an entire config structure.
* 
*   Notes:
*     - Be aware that any string pointers retrieved from the config structure will
*       become invalid upon calling this.
*/
void    mtConfigFree( mt_config* pHead );

/************************************************************************************************/
/*
*   Get Config
*
*   Notes:
*     - String: "Str"  -> "Str"
*     - Int   : "99"   ->  99
*     - Hex   : "FF"   -> 255
*     - Oct   : "77"   ->  63
*     - Float : "0.9"  -> 0.9
*     - Bool  : "True" -> true
*/
/****** Get *************************************************************************************/
/*
*   Description:
*     Get the raw string (no escape '\' conversion) from a config entry.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*     - def         : default return value
*
*   Returns:
*     String in the config entry; or 'def' if the entry does not exist.
*/
const c8* mtConfigGetString( const mt_config* pHead, const c8* puSect, const c8* puKey, const c8* def );
/*
*   Description:
*     Get the interpreted integer value from a config entry, with seperate functions for each
*   interpretation method.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*     - def         : default return value
*
*   Returns:
*     Integer value of the config entry; or 'def' if the entry does not exist.
*/
i32     mtConfigGetInt( const mt_config* pHead, const c8* puSect, const c8* puKey, i32 def );
u32     mtConfigGetHex( const mt_config* pHead, const c8* puSect, const c8* puKey, u32 def );
i32     mtConfigGetOct( const mt_config* pHead, const c8* puSect, const c8* puKey, i32 def );
/*
*   Description:
*     Get the interpreted floating point value from a config entry.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*     - def         : default return value
*
*   Returns:
*     Float value of the config entry; or 'def' if the entry does not exist.
*/
f64     mtConfigGetFloat( const mt_config* pHead, const c8* puSect, const c8* puKey, f64 def );
/*
*   Description:
*     Get interpreted boolean value from a config entry.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*     - def         : default return value
*
*   Returns:
*     Boolean value of the config entry; or 'def' if the entry does not exist, or does not
*   match either "True" or "False".
*/
bool    mtConfigGetBool( const mt_config* pHead, const c8* puSect, const c8* puKey, bool def );

/************************************************************************************************/
/*
*   Set Config
*
*   Notes:
*     - If an entry doesn't exist when using 'Set', the entry will be created (section+item).
*/
/****** Set *************************************************************************************/
/*
*   Description:
*     Set a config entry's raw string value. 
*
*   Notes:
*     - Any escape sequences will be converted to raw character pairs ('\r' -> '\\', 'r')
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*     - set         : string to set
*/
void    mtConfigSetString( mt_config* pHead, const c8* puSect, const c8* puKey, const c8* set );
/*
*   Description:
*     Set a config entry's value, as an integer.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*     - set         : string to set
*/
void    mtConfigSetInt( mt_config* pHead, const c8* puSect, const c8* puKey, i32 set );
void    mtConfigSetHex( mt_config* pHead, const c8* puSect, const c8* puKey, u32 set );
void    mtConfigSetOct( mt_config* pHead, const c8* puSect, const c8* puKey, i32 set );
/*
*   Description:
*     Set a config entry's value, as a float.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*     - set         : string to set
*/
void    mtConfigSetFloat( mt_config* pHead, const c8* puSect, const c8* puKey, f64 set );
/*
*   Description:
*     Set a config entry's value, as a boolean.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*     - set         : string to set
*/
void    mtConfigSetBool( mt_config* pHead, const c8* puSect, const c8* puKey, bool set );

/************************************************************************************************/
/*
*   Remove Config
*/
/****** Remove **********************************************************************************/
/*
*   Description:
*     Remove a section from a config structure, including all items contained within it.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*/
void    mtConfigRemSect( mt_config* pHead, const c8* puSect );
/*
*   Description:
*     Remove an item from a config structure.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item key
*/
void    mtConfigRemItem( mt_config* pHead, const c8* puSect, const c8* puKey );

/************************************************************************************************/
/*
*   Advanced Config Header
*/
/****** Print Out *******************************************************************************/
/*
*   Description:
*     Print contents of a config structure to a file stream.
*
*   Parameters:
*     - pHead       : config structure header
*     - f           : file stream
*/
void    mtConfigOut( const mt_config* pHead, FILE* f );

/****** Is Empty ********************************************************************************/
/*
*   Description:
*     Check if a config structure is empty (no sections and/or items).
*
*   Parameters:
*    - pHead        : config structure header
*
*   Returns:
*     'true' if empty; 'false' if the structure contains something.
*/
bool    mtConfigIsEmpty( const mt_config* pHead );

/****** Section Attribute ***********************************************************************/
/*
*   Description:
*     Get the number of config sections currently in a config structure.
*
*   Parameters:
*    - pHead        : config structure header
*
*   Returns:
*     Number of sections in the config structure.
*/
size    mtConfigGetSectNum( const mt_config* pHead );
/*
*   Description:
*     Get a config section structure from a config header.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*
*   Returns:
*     Config section; or 'nullptr' if the section doesn't exist.
*/
mt_config_sect* mtConfigGetSect( const mt_config* pHead, const c8* puSect );
/*
*   Description:
*     Get a config section structure from a config header.
*
*   Parameters:
*     - pHead       : config structure header
*     - ixSect      : config section index
*
*   Returns:
*     Config section; or 'nullptr' if the section doesn't exist.
*/
mt_config_sect* mtConfigGetSectByIndex( const mt_config* pHead, size ixSect );

/****** Item Attribute **************************************************************************/
/*
*   Description:
*     Get a config entry from a config header.
*
*   Parameters:
*     - pHead       : config structure header
*     - puSect      : config section name                                           [opt: NULL]
*     - puKey       : config item name
*
*   Returns:
*     Config item; or 'nullptr' if the item doesn't exist.
*/
mt_config_item* mtConfigGetItem( const mt_config* pHead, const c8* puSect, const c8* key );

/************************************************************************************************/
/*
*   Advanced Config Section
*/
/****** Get Attribute ***************************************************************************/
/*
*   Description:
*     Get config section name.
*
*   Parameters:
*     - pSect       : config section
*
*   Returns:
*     Name string of section; or 'nullptr' if section is global/nameless.
*/
const c8* mtConfigSectGetName( const mt_config_sect* pSect );

/****** Item Attribute **************************************************************************/
/*
*   Description:
*     Get the number of config items currently in a config section.
*
*   Parameters:
*     - pSect       : config section
*
*   Returns:
*     Number of sections in the config structure.
*/
size    mtConfigSectGetItemNum( const mt_config_sect* pSect );
/*
*   Description:
*     Get a config item from a config section by name.
*
*   Parameters:
*    - pSect        : config section
*    - puKey        : config item key
*
*   Returns:
*     Config section; or 'nullptr' if the section doesn't exist.
*/
mt_config_item* mtConfigSectGetItem( const mt_config_sect* pSect, const c8* puKey );
/*
*   Description:
*     Get a config item from a config section by index.
*
*   Parameters:
*     - pSect       : config section
*     - ixItem      : config item index
*
*   Returns:
*     Config section; or 'nullptr' if the section doesn't exist.
*/
mt_config_item* mtConfigSectGetItemByIndex( const mt_config_sect* pSect, size ixItem );

/****** Free ************************************************************************************/
/*
*   Description:
*     Free a config section structure, and all entries it contains.
*
*   Parameters:
*     - pSect       : config section
*/
void    mtConfigSectFree( mt_config_sect* pSect );

/************************************************************************************************/
/*
*   Advanced Config Item
*/
/****** Get Attribute ***************************************************************************/
/*
*   Description:
*     Get config item name/key.
*
*   Parameters:
*     - pItem       : config item
*/
const c8* mtConfigItemGetName( const mt_config_item* pItem );
/*
*   Description:
*     Get config item string value.
*
*   Parameters:
*     - pItem       : config item
*/
const c8* mtConfigItemGetValue( const mt_config_item* pItem );

/****** Free ************************************************************************************/
/*
*   Description:
*     Free a config item.
*
*   Parameters:
*     - pItem       : config item
*/
void    mtConfigItemFree( mt_config_item* pItem );

EXTERN_END

#endif/*H_SAMT_CONFIG*/
